import { Html, Head, Main, NextScript } from 'next/document'

export default function Document() {
  return (
    <Html>
      <Head>
        <meta name="description" content="Generated by create-t3-app" />
      </Head>

      <body>
        <Main />
        <NextScript />
      </body>
    </Html>
  )
}
